main: com.minegusta.mgapocalypse.Main
author: janie177
name: MGApocalypse
version: ${project.version}
softdepend: [WorldGuard]
depend: [MGLoot]
commands:
  mga:
    usage: /mga <parameters>
    description: Manage the wasteland world.
    aliases: [minegustaapocalypse, mgw]
    default: op
  break:
    usage: /break
    description: Pause playing wasteland.
    aliases: [hub, pause, logout, log-out, leave, abort, exit]
    default: true
  info:
    usage: /info [name]
    description: Show your stats.
    aliases: [stats, kills, deaths, points, chests, showstats, menu, help, showinfo, infomenu, statmenu, i]
    default: true
  perk:
    usage: /perk
    description: Show the perk menu.
    aliases: [perks, abilities, upgrades, upgrade, ability, shop, upgrademenu, perkshop]
    default: true